//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWebService")]
public interface IWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Factorial", ReplyAction="http://tempuri.org/IWebService/FactorialResponse")]
    int Factorial(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Factorial", ReplyAction="http://tempuri.org/IWebService/FactorialResponse")]
    System.Threading.Tasks.Task<int> FactorialAsync(int value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebServiceChannel : IWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServiceClient : System.ServiceModel.ClientBase<IWebService>, IWebService
{
    
    public WebServiceClient()
    {
    }
    
    public WebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Factorial(int value)
    {
        return base.Channel.Factorial(value);
    }
    
    public System.Threading.Tasks.Task<int> FactorialAsync(int value)
    {
        return base.Channel.FactorialAsync(value);
    }
}
